### ISSUE TITLE
[Everyone] Mission statement and core value list

### ISSUE THREAD

**Issue by laveshaparker** [ProgressiveHackNight/admin#6]
As discussed in our May 22 meeting, the time has come for us to formalize our mission statement, guidelines, and core values as an organization.

**For everyone:**
What does Progressive HackNight mean to you?
What are ProgHackNight's core values?
Write a 1-3 sentence draft mission statement.

**Optional**
What does the word Progressive Mean to you?

Let's aim to have this in by 6/12! You can just add your views as a comment to this ticket. I'll put reminders in the channel. Thanks!

**Comment by ibrand** [comment]
@laveshaparker We now are past the 5/29 meeting. I think it would be awesome to modify this ticket to the following:

**For everyone:**
What does Progressive HackNight mean to you?
What are ProgHackNight's core values?
Write a 1-3 sentence draft mission statement.

**Optional**
What does the word Progressive Mean to you?

And to put a deadline on this. Should take no more than 20 min to do.

**Comment by laveshaparker** [comment]
Sounds good! Updating this now :)

**Comment by julianrad** [comment]
What does Progressive HackNight mean to you?
PHN is ... (more to come)

What are ProgHackNight's core values?
Curiosity: we want to talk and listen and discuss and feel together in order to better understand our world and our society.  Inclusivity: we embrace a diverse group of perspectives and experiences and approaches to add to the robust strength of our work. Collaboration: we're all in this together and together we can achieve everything.

Write a 1-3 sentence draft mission statement. (from the PHN Session Document: https://docs.google.com/document/d/1JOMIVaK6u_j-NLmzBxtKgsspV9MFkkXVnqx9QEKs3nM/edit#)
Statement:
We’re about making great ideas happen.

Our Mission:
Borne from the collective Prog Code, <Progressive HackNight> is a bi-weekly gathering of coders and creatives, makers and doers, to foment and inspire action as well as use our collective talents and abilities to push forward progressive policy and pro-social change in benefit of the common good.

**Comment by julianrad** [comment]
And here's my notes from the last meeting:

Ilona:
What is Progressive Hack Night?
PHN is a combination of a coworking space, social space chaotic space within which lots of people from different industries come together to talk about progressive and social good projects. Through discussion, idea forming, sitting and coding together. as an org, the mission is to give space, empower people, make better pitches organize groups, organize sub groups to give them space to be heard - a conduit for productivity, encourage community and be inspired.

What does Progressive mean to you:
Progressive is a term that is pinned to politics meaning “highly left” - as a movement, with direction - pushing in that direction. For me it’s a mentality that change is a good thin and things need building and need help to get there.
Progressive is flavors of change that they’re looking to enact. Progressive is “about change” - conservative is resistant to change or regressive.

Vesha:
What is Progressive Hack Night?
PHN is a physical space that in some way provides an alternative to what we find when we work on open source software - give everyone IRL space to meet each other and allow them room to find people with whom they want to collaborate. Anything within progressive movement but also social good projects, and how does that make us different than betaNYC, et al

What does Progressive mean to you:
Progressivism comes from history and people are resistant to change - but change is what makes life better. Any change that embraces basic human rights. More politically focused than socially - more human centered focus.

Rapi:
What is Progressive Hack Night?
Social good is good - humanitarianism is progressivism. Nexus of technology and activism. huge gap between organizers and organizers and technologists - they don’t understand each other - as such technologies can’t make products for organizations that are good because they don’t communicate their needs well. PHN is a platform for those two to talk and to provide solutions and connections to solve that problem. Not just political, not just social good, but a platform for people to build relationships. That’s something that no online platform can provide. That’s the difference that PHN has from BetaNYC and others. 

What does Progressive mean to you:
What I really mean is communism! (NOTE FROM ME: Rapi was kidding) Progressivism is a discussion of justice. Wage justice, wage equality, gender equality, lessening inequality. THat’s where progressivism is and how it’s going to move forward. Providing for those who don’t have from a social point of view. Always looking forward for change. Change to reduce inequality. How can we provide these changes in a way that reduces inequality. and gets rid of money in politics.

Annie:
What is Progressive Hack Night?
 The collaboration of technologists from different areas - having them all come together and talk about what’s going on and find new ways to work together in a physical space - that’s exciting. It’s a framework to do that. Space and opportunity for people to hear about what’s going on.

What does Progressive mean to you:
Explicitly political. it has an explicitly political bent to it but it’s beyond a party platform. It’s a vision of the future of the country and what we want to see from our government and our future. Progressivism means moving forward and to see the role of our government to help the people who need it most and advance social inequality. And moving forward better political attitudes in our government and our attitudes.

Tino:
What is Progressive Hack Night?
Safe space for locals. People come together and talk about the progressive movement and how technologists can help. People come in with projects, talk about their ideas, and find people to work on stuff. Exciting thing is people coming in - finding progressive solutions to problems. But what are we working on progressive 

What does Progressive mean to you:
Progressive to me is more of a change towards social conditioning - or a conditioning that is step by step, it’s a social change that happens in a step by step form that takes a long time. it’s about people more than political groups - happens in people first, then political groups later. Progressive is about people and less about groups. It’s about what they feel, what they feel emotionally towards others.

**Comment by rcscastillo** [comment]
Adding my own notes from the meeting! Also have to mention that progressivism as communism is tongue and cheek (as the tone was missed in text) 😄 

# What is hacknight?

## Ilona
A combination of a co-working space, a social space, and a bit of chaotic space. Where industries come together and social good projects come into the room. Through discussion, through ideas that are forming, through organizing, and as a goal our goal is to provide space and empower people. Even to kind of absorb subgroups and become the conduit for productivity. Allowing people to pass through it, create things and feel inspired. 
 
## Vesha
Progressive hacknight is a physical space that in someways different for when we work on opensource software, and allow bonds and provide ways for them to spend their time to. Anything within the progressive movement, but social good projects is key as well. That doesn’t make us different from 
 
## Rapi
Progressive hacknight is a platform
 
## Annie
What makes me want to come back? The sort of collaboration of technologists from different areas and being able to come together and hear from each other and find ways to collaborate better. And do it in a physical space is really exciting. It’s a framework to do that, it’s open in a way to provide space and opportunity to hear about what everybody else is doing and working together. 
 
## Tino
It’s a place to come together and discuss progressive issues and find solutions. As a project owners, a lot of people are coming in as project owners, build meaningful relationships, and find people work on progressive projects. Coming back, is the relationships and projects. Find progressive solutions. I do love the idea that we are also working on social good projects, if we are working on progressive ideas, will we be attracting the right people to work on these projects.

**Comment by julianrad** [comment]
Sorry Rapi, I meant to clean up my messy notes. Apologies!

**Comment by laveshaparker** [comment]
##### What does Progressive HackNight mean to you?
"Progressive HackNight" implies a community that tackles issues in the progressive political and social space. They allocate resources (usually in the form of people and time) toward addressing problems they encounter, and use personal connections to form a more powerful network in the NYC activist community at large.

##### What are ProgHackNight's core values?
- Effectiveness. The whole purpose of our hacknight is to create positive change in our city, country, and world.
- Openness. This is a group open to activists, creatives, programmers, and designers of all experience levels.
- Safety. Any well-meaning person should feel welcome and useful within our community.
- Empowerment. If someone has an idea or passion and wants to work hard to address it, we will support them and help them see it through.

##### Write a 1-3 sentence draft mission statement.
We are an organization of progressively-minded activists, citizens, and technologists who meet in-person to build tools that can be used to diminish inequality in our society. In doing so, we empower anyone with a vision to engage the people they need to bring it to fruition, and provide an outlet for engineers, designers, and creatives to use their skills toward initiatives they believe in, resulting in positive change in the world.

##### **Bonus** My personal end vision for Progressive HackNight
A bi-weekly meetup of progressives, in which activists and concerned citizens can bring background knowledge and define a problem space to programmers, designers, and creatives. They can develop a concrete plan around how to address the issue and execute it in a timely manner in subsequent meetings, all while enjoying the social benefit of belonging to a circle of progressives.

##### Optional
###### What does the word "Progressive" mean to you
"Progressive" is mapped closely to [humanism](https://en.wikipedia.org/wiki/Humanism) to me. It is a constant effort to ensure that all humans are equally valued, reduce inequality among people, and make whatever change is necessary to achieve that equality.

**Comment by laveshaparker** [comment]
Also sorry, I accidentally cleared the assignees while trying to add Julian! 😅

**Comment by julianrad** [comment]
OK on the mission statement stuff, here's what we came up with in our working group tonight:

Statement:
We’re about making great ideas happen.

Mission:
XXXXXX is a bi-weekly gathering of coders and creatives, makers and doers, to foment and inspire action. We use our collective talents and abilities to push forward pro-social change in benefit of the common good.

**Comment by ibrand** [comment]
**What does Progressive HackNight mean to you**
This was addressed in what I said at the meeting which was so wonderfully note-taken by rapi and Julian, but basically I see Prog HackNight as a collective of passionate movers and shakers who are looking to do good through technology. I see the event itself as a caucus of those people and as a conduit for connecting them and create a safe and productive space for them to do good work.

**What are Progressive HackNight's Core Values**
*I loved vesha's answer to this question BTW, but I'm trying to dig deep and give a unique answer*
- Compassion. Namely, we should embody the change we want to see in the world in the way we structure our events, and in the way we treat each other.
- Effectiveness. (Sorry vesha I totally stole this one. It's just so true)
- Uplifting Voices. Similar to vesha's "Empowerment" with the added sentiment of making sure that the quiet are heard and the loud make space.

**Mission Statement**
See Julian's post above, I helped co-write that at the last hack night and feel like it does a good job summing us up quickly.

**Comment by rapicastillo** [comment]
I love the mission statement @ibrand & @julianrad ! One thing I would like to ask / suggest (maybe this will be more on the goals and objectives), is to how we can bridge the gap or provide service to grassroots organizations that need tech help. 

Also love Vesha's points. I think those values are spot on.

**Comment by ibrand** [comment]
Yeah @rapicastillo that's a totally real question. I think the Mission statement makes room for that without full on outlining how we'll do it. I think it'd be a great thing to build into goals.

**Comment by laveshaparker** [comment]
I completely agree!
> added sentiment of making sure that the quiet are heard and the loud make space.

**Comment by laveshaparker** [comment]
Where do we stand on this? Should we get any remaining statements at the next hacknight meeting?

**Comment by julianrad** [comment]
It's my understanding that we're good with the strap line and the mission statement. Next up is defining our values which we've started but haven't really tackled properly.

**Comment by laveshaparker** [comment]
I think we can probably close this. Feel free to re-open with a description of what remains to be done if you think it shouldn't be closed!
